export const XML_HEADER = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n';

export const RELS_CORE_PROPS = 'http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties';
export const RELS_EXT_PROPS = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties';
export const RELS_WS = [
  "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet",
  "http://purl.oclc.org/ooxml/officeDocument/relationships/worksheet"
];
export const RELS = {
  WB: "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument",
  SHEET: "http://sheetjs.openxmlformats.org/officeDocument/2006/relationships/officeDocument",
  HLINK: "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink",
  VML: "http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing",
  VBA: "http://schemas.microsoft.com/office/2006/relationships/vbaProject",
  THEME: "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme",
  STY: "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles",
};

export const WS_XML_ROOT = '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">';
export const CORE_ROOT = '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>';
export const WB_XML_ROOT = '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">';
const STYLES_XML_ROOT = '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">';
export const EXT_PROPS_XML_ROOT = '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">';
export const RELS_ROOT = '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">';
export const CTYPE_XML_ROOT = '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">';

export const EXT_PROPS = [
  ["Application", "Application", "string"],
  ["AppVersion", "AppVersion", "string"],
  ["Company", "Company", "string"],
  ["DocSecurity", "DocSecurity", "string"],
  ["Manager", "Manager", "string"],
  ["HyperlinksChanged", "HyperlinksChanged", "bool"],
  ["SharedDoc", "SharedDoc", "bool"],
  ["LinksUpToDate", "LinksUpToDate", "bool"],
  ["ScaleCrop", "ScaleCrop", "bool"],
  ["HeadingPairs", "HeadingPairs", "raw"],
  ["TitlesOfParts", "TitlesOfParts", "raw"]
];

export const THEME = [
  XML_HEADER,
  '<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Office Theme">',
  '<a:themeElements>',
  '<a:clrScheme name="Office">',
  '<a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1>',
  '<a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1>',
  '<a:dk2><a:srgbClr val="1F497D"/></a:dk2>',
  '<a:lt2><a:srgbClr val="EEECE1"/></a:lt2>',
  '<a:accent1><a:srgbClr val="4F81BD"/></a:accent1>',
  '<a:accent2><a:srgbClr val="C0504D"/></a:accent2>',
  '<a:accent3><a:srgbClr val="9BBB59"/></a:accent3>',
  '<a:accent4><a:srgbClr val="8064A2"/></a:accent4>',
  '<a:accent5><a:srgbClr val="4BACC6"/></a:accent5>',
  '<a:accent6><a:srgbClr val="F79646"/></a:accent6>',
  '<a:hlink><a:srgbClr val="0000FF"/></a:hlink>',
  '<a:folHlink><a:srgbClr val="800080"/></a:folHlink>',
  '</a:clrScheme>',
  '<a:fontScheme name="Office">',
  '<a:majorFont>',
  '<a:latin typeface="Cambria"/>',
  '<a:ea typeface=""/>',
  '<a:cs typeface=""/>',
  '<a:font script="Jpan" typeface="ＭＳ Ｐゴシック"/>',
  '<a:font script="Hang" typeface="맑은 고딕"/>',
  '<a:font script="Hans" typeface="宋体"/>',
  '<a:font script="Hant" typeface="新細明體"/>',
  '<a:font script="Arab" typeface="Times New Roman"/>',
  '<a:font script="Hebr" typeface="Times New Roman"/>',
  '<a:font script="Thai" typeface="Tahoma"/>',
  '<a:font script="Ethi" typeface="Nyala"/>',
  '<a:font script="Beng" typeface="Vrinda"/>',
  '<a:font script="Gujr" typeface="Shruti"/>',
  '<a:font script="Khmr" typeface="MoolBoran"/>',
  '<a:font script="Knda" typeface="Tunga"/>',
  '<a:font script="Guru" typeface="Raavi"/>',
  '<a:font script="Cans" typeface="Euphemia"/>',
  '<a:font script="Cher" typeface="Plantagenet Cherokee"/>',
  '<a:font script="Yiii" typeface="Microsoft Yi Baiti"/>',
  '<a:font script="Tibt" typeface="Microsoft Himalaya"/>',
  '<a:font script="Thaa" typeface="MV Boli"/>',
  '<a:font script="Deva" typeface="Mangal"/>',
  '<a:font script="Telu" typeface="Gautami"/>',
  '<a:font script="Taml" typeface="Latha"/>',
  '<a:font script="Syrc" typeface="Estrangelo Edessa"/>',
  '<a:font script="Orya" typeface="Kalinga"/>',
  '<a:font script="Mlym" typeface="Kartika"/>',
  '<a:font script="Laoo" typeface="DokChampa"/>',
  '<a:font script="Sinh" typeface="Iskoola Pota"/>',
  '<a:font script="Mong" typeface="Mongolian Baiti"/>',
  '<a:font script="Viet" typeface="Times New Roman"/>',
  '<a:font script="Uigh" typeface="Microsoft Uighur"/>',
  '<a:font script="Geor" typeface="Sylfaen"/>',
  '</a:majorFont>',
  '<a:minorFont>',
  '<a:latin typeface="Calibri"/>',
  '<a:ea typeface=""/>',
  '<a:cs typeface=""/>',
  '<a:font script="Jpan" typeface="ＭＳ Ｐゴシック"/>',
  '<a:font script="Hang" typeface="맑은 고딕"/>',
  '<a:font script="Hans" typeface="宋体"/>',
  '<a:font script="Hant" typeface="新細明體"/>',
  '<a:font script="Arab" typeface="Arial"/>',
  '<a:font script="Hebr" typeface="Arial"/>',
  '<a:font script="Thai" typeface="Tahoma"/>',
  '<a:font script="Ethi" typeface="Nyala"/>',
  '<a:font script="Beng" typeface="Vrinda"/>',
  '<a:font script="Gujr" typeface="Shruti"/>',
  '<a:font script="Khmr" typeface="DaunPenh"/>',
  '<a:font script="Knda" typeface="Tunga"/>',
  '<a:font script="Guru" typeface="Raavi"/>',
  '<a:font script="Cans" typeface="Euphemia"/>',
  '<a:font script="Cher" typeface="Plantagenet Cherokee"/>',
  '<a:font script="Yiii" typeface="Microsoft Yi Baiti"/>',
  '<a:font script="Tibt" typeface="Microsoft Himalaya"/>',
  '<a:font script="Thaa" typeface="MV Boli"/>',
  '<a:font script="Deva" typeface="Mangal"/>',
  '<a:font script="Telu" typeface="Gautami"/>',
  '<a:font script="Taml" typeface="Latha"/>',
  '<a:font script="Syrc" typeface="Estrangelo Edessa"/>',
  '<a:font script="Orya" typeface="Kalinga"/>',
  '<a:font script="Mlym" typeface="Kartika"/>',
  '<a:font script="Laoo" typeface="DokChampa"/>',
  '<a:font script="Sinh" typeface="Iskoola Pota"/>',
  '<a:font script="Mong" typeface="Mongolian Baiti"/>',
  '<a:font script="Viet" typeface="Arial"/>',
  '<a:font script="Uigh" typeface="Microsoft Uighur"/>',
  '<a:font script="Geor" typeface="Sylfaen"/>',
  '</a:minorFont>',
  '</a:fontScheme>',
  '<a:fmtScheme name="Office">',
  '<a:fillStyleLst>',
  '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>',
  '<a:gradFill rotWithShape="1">',
  '<a:gsLst>',
  '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="50000"/><a:satMod val="300000"/></a:schemeClr></a:gs>',
  '<a:gs pos="35000"><a:schemeClr val="phClr"><a:tint val="37000"/><a:satMod val="300000"/></a:schemeClr></a:gs>',
  '<a:gs pos="100000"><a:schemeClr val="phClr"><a:tint val="15000"/><a:satMod val="350000"/></a:schemeClr></a:gs>',
  '</a:gsLst>',
  '<a:lin ang="16200000" scaled="1"/>',
  '</a:gradFill>',
  '<a:gradFill rotWithShape="1">',
  '<a:gsLst>',
  '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="100000"/><a:shade val="100000"/><a:satMod val="130000"/></a:schemeClr></a:gs>',
  '<a:gs pos="100000"><a:schemeClr val="phClr"><a:tint val="50000"/><a:shade val="100000"/><a:satMod val="350000"/></a:schemeClr></a:gs>',
  '</a:gsLst>',
  '<a:lin ang="16200000" scaled="0"/>',
  '</a:gradFill>',
  '</a:fillStyleLst>',
  '<a:lnStyleLst>',
  '<a:ln w="9525" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"><a:shade val="95000"/><a:satMod val="105000"/></a:schemeClr></a:solidFill><a:prstDash val="solid"/></a:ln>',
  '<a:ln w="25400" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln>',
  '<a:ln w="38100" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln>',
  '</a:lnStyleLst>',
  '<a:effectStyleLst>',
  '<a:effectStyle>',
  '<a:effectLst>',
  '<a:outerShdw blurRad="40000" dist="20000" dir="5400000" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="38000"/></a:srgbClr></a:outerShdw>',
  '</a:effectLst>',
  '</a:effectStyle>',
  '<a:effectStyle>',
  '<a:effectLst>',
  '<a:outerShdw blurRad="40000" dist="23000" dir="5400000" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="35000"/></a:srgbClr></a:outerShdw>',
  '</a:effectLst>',
  '</a:effectStyle>',
  '<a:effectStyle>',
  '<a:effectLst>',
  '<a:outerShdw blurRad="40000" dist="23000" dir="5400000" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="35000"/></a:srgbClr></a:outerShdw>',
  '</a:effectLst>',
  '<a:scene3d><a:camera prst="orthographicFront"><a:rot lat="0" lon="0" rev="0"/></a:camera><a:lightRig rig="threePt" dir="t"><a:rot lat="0" lon="0" rev="1200000"/></a:lightRig></a:scene3d>',
  '<a:sp3d><a:bevelT w="63500" h="25400"/></a:sp3d>',
  '</a:effectStyle>',
  '</a:effectStyleLst>',
  '<a:bgFillStyleLst>',
  '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>',
  '<a:gradFill rotWithShape="1">',
  '<a:gsLst>',
  '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="40000"/><a:satMod val="350000"/></a:schemeClr></a:gs>',
  '<a:gs pos="40000"><a:schemeClr val="phClr"><a:tint val="45000"/><a:shade val="99000"/><a:satMod val="350000"/></a:schemeClr></a:gs>',
  '<a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="20000"/><a:satMod val="255000"/></a:schemeClr></a:gs>',
  '</a:gsLst>',
  '<a:path path="circle"><a:fillToRect l="50000" t="-80000" r="50000" b="180000"/></a:path>',
  '</a:gradFill>',
  '<a:gradFill rotWithShape="1">',
  '<a:gsLst>',
  '<a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="80000"/><a:satMod val="300000"/></a:schemeClr></a:gs>',
  '<a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="30000"/><a:satMod val="200000"/></a:schemeClr></a:gs>',
  '</a:gsLst>',
  '<a:path path="circle"><a:fillToRect l="50000" t="50000" r="50000" b="50000"/></a:path>',
  '</a:gradFill>',
  '</a:bgFillStyleLst>',
  '</a:fmtScheme>',
  '</a:themeElements>',
  '<a:objectDefaults>',
  '<a:spDef>',
  '<a:spPr/><a:bodyPr/><a:lstStyle/><a:style><a:lnRef idx="1"><a:schemeClr val="accent1"/></a:lnRef><a:fillRef idx="3"><a:schemeClr val="accent1"/></a:fillRef><a:effectRef idx="2"><a:schemeClr val="accent1"/></a:effectRef><a:fontRef idx="minor"><a:schemeClr val="lt1"/></a:fontRef></a:style>',
  '</a:spDef>',
  '<a:lnDef>',
  '<a:spPr/><a:bodyPr/><a:lstStyle/><a:style><a:lnRef idx="2"><a:schemeClr val="accent1"/></a:lnRef><a:fillRef idx="0"><a:schemeClr val="accent1"/></a:fillRef><a:effectRef idx="1"><a:schemeClr val="accent1"/></a:effectRef><a:fontRef idx="minor"><a:schemeClr val="tx1"/></a:fontRef></a:style>',
  '</a:lnDef>',
  '</a:objectDefaults>',
  '<a:extraClrSchemeLst/>',
  '</a:theme>',
].join("");

export const STYLE = [
  XML_HEADER,
  STYLES_XML_ROOT,
  '<numFmts count="1"><numFmt numFmtId="56" formatCode="&quot;上午/下午 &quot;hh&quot;時&quot;mm&quot;分&quot;ss&quot;秒 &quot;"/></numFmts>',
  '<fonts count="1"><font><sz val="12"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font></fonts>',
  '<fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills>',
  '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>',
  '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>',
  '<cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs>',
  '<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles><dxfs count="0"/>',
  '<tableStyles count="0" defaultTableStyle="TableStyleMedium9" defaultPivotStyle="PivotStyleMedium4"/></styleSheet>',
].join('');

export const type2ct = {
  rels: "application/vnd.openxmlformats-package.relationships+xml",
  themes: "application/vnd.openxmlformats-officedocument.theme+xml",
  coreprops: "application/vnd.openxmlformats-package.core-properties+xml",
  extprops: "application/vnd.openxmlformats-officedocument.extended-properties+xml",
};

export const CTYPE_DEFAULTS_ARRAY = [
  ["xml", "application/xml"],
  ["bin", "application/vnd.ms-excel.sheet.binary.macroEnabled.main"],
  ["vml", "application/vnd.openxmlformats-officedocument.vmlDrawing"],
  /* from test files */
  ["bmp", "image/bmp"],
  ["png", "image/png"],
  ["gif", "image/gif"],
  ["emf", "image/x-emf"],
  ["wmf", "image/x-wmf"],
  ["jpg", "image/jpeg"],
  ["jpeg", "image/jpeg"],
  ["tif", "image/tiff"],
  ["tiff", "image/tiff"],
  ["pdf", "application/pdf"],
  ["rels", type2ct.rels]
];

export const CT_LIST = {
  "workbooks": {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml",
    "xlsm": "application/vnd.ms-excel.sheet.macroEnabled.main+xml",
    "xlsb": "application/vnd.ms-excel.sheet.binary.macroEnabled.main",
    "xlam": "application/vnd.ms-excel.addin.macroEnabled.main+xml",
    "xltx": "application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml"
  }, 
  "strs": {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml",
    "xlsb": "application/vnd.ms-excel.sharedStrings",
    "xlsm": "application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml",
    "xlam": "application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"
  }, 
  "comments": {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml",
    "xlsb": "application/vnd.ms-excel.comments",
    "xlsm": "application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml",
    "xlam": "application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml"
  }, 
  "sheets": {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml",
    "xlsb": "application/vnd.ms-excel.worksheet",
    "xlsm": "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml",
    "xlam": "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"
  }, 
  "charts": {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.chartsheet+xml",
    "xlsb": "application/vnd.ms-excel.chartsheet",
    "xlsm": "application/vnd.openxmlformats-officedocument.spreadsheetml.chartsheet+xml",
    "xlam": "application/vnd.openxmlformats-officedocument.spreadsheetml.chartsheet+xml"
  }, 
  "dialogs": {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.dialogsheet+xml",
    "xlsb": "application/vnd.ms-excel.dialogsheet",
    "xlsm": "application/vnd.openxmlformats-officedocument.spreadsheetml.dialogsheet+xml",
    "xlam": "application/vnd.openxmlformats-officedocument.spreadsheetml.dialogsheet+xml"
  },
  "macros": {
    "xlsx": "application/vnd.ms-excel.macrosheet+xml",
    "xlsb": "application/vnd.ms-excel.macrosheet",
    "xlsm": "application/vnd.ms-excel.macrosheet+xml",
    "xlam": "application/vnd.ms-excel.macrosheet+xml"
  },
  "styles": {
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml",
    "xlsb": "application/vnd.ms-excel.styles",
    "xlsm": "application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml", 
    "xlam": "application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"
  }
};